"""Published weekly-review figures, frozen against a production snapshot slice.

These are deliberately expectations from the reviews, not values generated by
re-running a current report and copying its output into the test.

Every one runs **twice**: once against the snapshot slice and once against a D3
vault built from it (T-007). The vault keeps every derived table and drops raw
samples for all but six series, so a figure that reproduces from the snapshot
and not from the vault is a figure the product would silently lose. That is the
only way to find out which, short of shipping.
"""
from __future__ import annotations

import sqlite3
from statistics import fmean

import pytest

from health_advisor import analysis as A
from health_advisor import vault
from tests.fixtures.golden_snapshot import (
    PRODUCTION_SNAPSHOT,
    build_golden_database,
)


if not PRODUCTION_SNAPSHOT.exists():
    pytest.skip(
        f"golden figures need the production snapshot at {PRODUCTION_SNAPSHOT}",
        allow_module_level=True,
    )


@pytest.fixture(scope="session")
def golden_slice(tmp_path_factory):
    """The production-derived slice: every series, as the snapshot has them."""
    path = tmp_path_factory.mktemp("golden-figures") / "health.db"
    build_golden_database(path)
    return path


@pytest.fixture(scope="session")
def golden_vault(tmp_path_factory, golden_slice):
    """The same slice after the D3 filter — six raw series instead of all of them.

    T-007's criterion is that the published figures reproduce *from a vault*,
    which is a different claim from reproducing from the snapshot: a vault drops
    the raw rows for every series outside `VAULT_RAW_SERIES`, including
    `body_mass` and `step_count`. Building it from the same slice means any
    figure that secretly depends on a dropped series fails here rather than in
    production, where the symptom would be a number quietly going missing.
    """
    path = tmp_path_factory.mktemp("golden-vault") / "vault.db"
    # measure_gzip is a report field and over half the build time here.
    vault.build_vault(golden_slice, path, owner="golden", measure_gzip=False)
    return path


@pytest.fixture(scope="session", params=["snapshot", "vault"])
def golden_conn(request, golden_slice, golden_vault):
    """Every assertion in this module runs twice: against the snapshot slice and
    against a vault built from it."""
    path = golden_slice if request.param == "snapshot" else golden_vault
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA query_only = ON")
    try:
        yield conn
    finally:
        conn.close()


def _daily_metric(conn, metric: str, start: str, end: str, column: str):
    return [
        row[0]
        for row in conn.execute(
            f"SELECT {column} FROM daily_metrics "
            "WHERE metric = ? AND date BETWEEN ? AND ? ORDER BY date",
            (metric, start, end),
        )
    ]


def _workout(conn, day: str, workout_type: str, index: int = 0):
    rows = conn.execute(
        "SELECT * FROM workouts WHERE local_date = ? AND workout_type = ? "
        "ORDER BY start_utc",
        (day, workout_type),
    ).fetchall()
    return rows[index]


def test_published_jog_minutes_and_pace(golden_conn):
    rows = {
        row["period_start"]: row
        for row in A.impact_volume(
            golden_conn, "2026-07-20", "2026-08-16", by="week"
        )
    }

    # The committed snapshot and its vault have no per-bucket step_count
    # stream. Under #193, distance/HR alone cannot produce dose-ceiling jog
    # minutes; the written review figures remain historical and immutable.
    for day in ("2026-07-20", "2026-07-27", "2026-08-03", "2026-08-10"):
        assert rows[day]["jog_minutes"] == pytest.approx(0.0)
    assert rows["2026-08-03"]["jog_pace_min_per_mi"] is None
    assert rows["2026-08-10"]["jog_pace_min_per_mi"] is None


def test_published_weekly_steps(golden_conn):
    def steps(start: str, end: str) -> float:
        return sum(_daily_metric(golden_conn, "step_count", start, end, "sum"))

    # Each review now carries a `Figures as of <timestamp>` line under its title,
    # so these bounds have a documented meaning: they are the room a published
    # figure needs because late samples move a historical total AFTER it is
    # published, not slack for an unexplained gap.
    #
    # They cannot become exact. Reconstructing "what did this window look like
    # on date D" was attempted on 2026-08-22 from ingest_log's cumulative
    # rows_added against record ids, and it missed by -9,487 / -12,133 / -10,749
    # steps on weeks 5, 6 and 7 (week 4 landed at -34, which is the near miss
    # that makes the method look workable). It cannot work: max(records.id) is
    # 14,031,573 against 13,900,746 rows, so 130,827 ids belong to deleted rows,
    # and sum(ingest_log.rows_added) undercuts the row count by a further
    # 155,589. An exact as-of query needs ingest provenance stored on the row.
    #
    # The window is part of the published claim and is read off the review's own
    # per-day figure, not assumed: "~55,100 (~7,900/day)" is 7 days, Mon-Sun,
    # while week 5's "~39,600 (~6,600/day)" is 6 and week 7 says Mon-Sat outright.
    # Summing the wrong window is what made #14 look like a 12.7% discrepancy.

    # week-04-review.md:58; the review says ~55,100, so a 350-step bound is
    # limited to the publication's rounding/revision scale.
    assert steps("2026-07-20", "2026-07-26") == pytest.approx(55100, abs=350)
    # week-05-review.md:54; ~39,600 at ~6,600/day is Mon-SAT. 550 bounds the
    # residual 1.3% drift without letting a materially different week pass.
    assert steps("2026-07-27", "2026-08-01") == pytest.approx(39600, abs=550)
    # week-06-review.md:50; the review says ~44,250, so 800 steps bounds the
    # rounded aggregate without making a materially different week pass.
    assert steps("2026-08-03", "2026-08-09") == pytest.approx(44250, abs=800)
    # week-07-review.md:49. The 63,161 published expectation stays, and the
    # cause of the drift is now measured rather than suspected (#15): the
    # snapshot reads 63,950.436, and the last 2,103 step_count rows on
    # 2026-08-15 by id (13284211-13286313) sum to 788.436005. Subtract them and
    # the total is 63,161.9998 — the published figure to within a step. Those
    # rows are id-contiguous with ingest_log batch 565, which landed
    # 2026-08-18T22:13:35Z, three days after the week closed and after the
    # review was written. `records` carries no ingest_id, so the attribution to
    # 565 is by id ordering; the arithmetic is exact either way.
    #
    # So the bound is not slack for an unexplained gap. It is the room a
    # published figure needs because late samples change a historical total
    # after it is published. Do NOT widen it to 63,950 — that would assert the
    # review said something it did not.
    assert steps("2026-08-10", "2026-08-15") == pytest.approx(63161, abs=850)


def test_published_weight_figures_use_daily_last(golden_conn):
    def weight(start: str, end: str):
        values = _daily_metric(golden_conn, "body_mass", start, end, "last")
        return len(values), fmean(values)

    n, value = weight("2026-07-20", "2026-07-26")
    # week-04-review.md:53; count is exact and 0.25 lb respects the ~ notation.
    assert n == pytest.approx(7, abs=0)
    assert value == pytest.approx(189.8, abs=0.25)

    n, value = weight("2026-07-27", "2026-08-02")
    # week-05-review.md:46; count is exact and 0.1 lb is tighter than the
    # review's one-decimal publication.
    assert n == pytest.approx(5, abs=0)
    assert value == pytest.approx(189.0, abs=0.1)

    n, value = weight("2026-08-10", "2026-08-15")
    # week-07-review.md:46; six readings are part of the published claim.
    assert n == pytest.approx(6, abs=0)
    assert value == pytest.approx(188.8, abs=0.1)


def test_published_resting_hr_figures_and_blocks(golden_conn):
    weekly = {
        row["week_start"]: row
        for row in A.weekly_series(
            golden_conn, "resting_heart_rate", "2026-07-20", "2026-08-16"
        )
    }

    # week-04-review.md:56; 0.5 bpm accommodates the review's approximate mean.
    assert weekly["2026-07-20"]["mean"] == pytest.approx(63.4, abs=0.5)
    # week-05-review.md:52; 0.5 bpm accommodates the review's approximate mean.
    assert weekly["2026-07-27"]["mean"] == pytest.approx(63.4, abs=0.5)
    # week-06-review.md:48; 0.5 bpm accommodates the review's rounded mean.
    assert weekly["2026-08-03"]["mean"] == pytest.approx(66.9, abs=0.5)
    # week-07-review.md:47; 0.1 bpm matches the published one-decimal block mean.
    assert weekly["2026-08-10"]["mean"] == pytest.approx(66.3, abs=0.1)

    def block(start: str, end: str):
        values = _daily_metric(
            golden_conn, "resting_heart_rate", start, end, "last"
        )
        return len(values), fmean(values)

    n, value = block("2026-06-24", "2026-07-21")
    # week-07-review.md:47; n is exact and 0.1 bpm matches the block display.
    assert n == pytest.approx(23, abs=0)
    assert value == pytest.approx(65.2, abs=0.1)

    n, value = block("2026-07-20", "2026-08-16")
    # week-07-review.md:47; n is exact and 0.1 bpm matches the block display.
    assert n == pytest.approx(28, abs=0)
    assert value == pytest.approx(64.9, abs=0.1)


def test_published_session_figures(golden_conn):
    tue_w4 = _workout(golden_conn, "2026-07-21", "running")
    # week-04-review.md:55; 0.2 min allows source-duration precision.
    assert tue_w4["duration_min"] == pytest.approx(41.0, abs=0.2)
    # week-04-review.md:55; 0.01 mi matches the published two-decimal distance.
    assert tue_w4["distance_mi"] == pytest.approx(2.04, abs=0.01)
    # week-04-review.md:55; 0.6 bpm allows the source summary's rounding.
    assert tue_w4["avg_heart_rate"] == pytest.approx(118, abs=0.6)
    # week-04-review.md:55; max HR is published as an integer, so tolerance is 0.
    assert tue_w4["max_heart_rate"] == pytest.approx(161, abs=0)

    wed_w4 = _workout(golden_conn, "2026-07-22", "running")
    # week-04-review.md:55; 0.3 bpm allows source-summary rounding.
    assert wed_w4["avg_heart_rate"] == pytest.approx(152, abs=0.3)
    # week-04-review.md:55; max HR is published as an integer, so tolerance is 0.
    assert wed_w4["max_heart_rate"] == pytest.approx(184, abs=0)

    sun_w6 = _workout(golden_conn, "2026-08-09", "running")
    # week-06-review.md:45; 0.1 min matches the published tenth of a minute.
    assert sun_w6["duration_min"] == pytest.approx(52.3, abs=0.1)
    # week-06-review.md:45; 0.01 mi matches the published two-decimal distance.
    assert sun_w6["distance_mi"] == pytest.approx(3.07, abs=0.01)
    # week-06-review.md:46; 0.3 bpm allows source-summary rounding.
    assert sun_w6["avg_heart_rate"] == pytest.approx(138, abs=0.3)

    hike = _workout(golden_conn, "2026-08-04", "walking")
    # week-06-review.md:20; 0.1 min matches the published duration precision.
    assert hike["duration_min"] == pytest.approx(135.9, abs=0.1)
    # week-06-review.md:20; 0.01 mi matches the published distance precision.
    assert hike["distance_mi"] == pytest.approx(6.14, abs=0.01)
    # week-06-review.md:20; 0.5 bpm allows the source summary's rounding.
    assert hike["avg_heart_rate"] == pytest.approx(118, abs=0.5)


def test_published_vo2_and_easy_block_figures(golden_conn):
    # week-04-review.md:57; 0.1 mL/min·kg matches the published one-decimal VO2.
    assert _daily_metric(
        golden_conn, "vo2_max", "2026-07-26", "2026-07-26", "last"
    )[0] == pytest.approx(37.4, abs=0.1)

    weekly_vo2 = A.weekly_series(
        golden_conn, "vo2_max", "2026-07-27", "2026-08-02"
    )[0]
    # week-05-review.md:53; 0.1 mL/min·kg matches the published one-decimal mean.
    assert weekly_vo2["mean"] == pytest.approx(37.4, abs=0.1)

    sun_w7 = _workout(golden_conn, "2026-08-15", "running")
    block = A.longest_block(
        golden_conn, sun_w7["start_utc"], sun_w7["end_utc"]
    )
    # week-07-review.md:42; 0.1 min matches bucket-derived display precision and
    # specifically uses the HR-qualified result, not the intensity-blind block.
    assert block["qualified_min"] == pytest.approx(9.3, abs=0.1)
    # week-07-review.md:42; 0.5 bpm allows the mean of irregular HR samples.
    assert block["avg_hr_longest_block"] == pytest.approx(145, abs=0.5)
    # week-07-review.md:42; 0.1 min checks the underlying bridged block as well.
    assert block["bridged_min"] == pytest.approx(9.3, abs=0.1)
