#!/usr/bin/env python3
"""Independent reference implementation of the D23 body AEAD, and its vectors.

This file exists to be a SECOND implementation. It is written from the scheme
below and deliberately imports nothing from ``health_advisor``, so the vectors
it emits are an oracle for the shipped layer rather than a transcript of it. A
vector file generated by the code it tests cannot fail; this one can, and the
server's own test must reproduce every ``wire_b64`` byte for byte.

Regenerate with::

    python scripts/d23_reference.py --out tests/fixtures/d23_body_aead_v1.json

and expect a clean ``git diff``: everything is deterministic, including the
nonces, which are drawn from a fixed counter rather than from the OS. THE
PRODUCTION PATH MUST NEVER DO THAT -- a repeated (key, nonce) pair under
AES-GCM leaks the XOR of two plaintexts and the authentication subkey. The
fixed nonces here are what makes a vector reproducible; the shipped sealer
takes ``os.urandom(12)`` and exposes an injectable nonce only to its tests.

The scheme
----------

Wire (one opaque body, request or response)::

    byte  0        version, 0x01
    bytes 1..8     timestamp_ms, uint64 big-endian
    bytes 9..20    nonce, 12 bytes
    bytes 21..     AES-256-GCM ciphertext || 16-byte tag

37 bytes of overhead. The timestamp rides INSIDE the envelope rather than in a
header: the AAD has to be reconstructible from the message alone, and a header
is the one part of the message an intermediary rewrites as a matter of course.
It appears twice on purpose -- once in the clear, which is what the receiver
parses, and once inside the AAD, which is what the tag authenticates. Editing
the clear copy changes the reconstructed AAD and the tag fails.

Keys::

    k_request  = HKDF-SHA256(ikm=secret_utf8, salt=HKDF_SALT,
                             info=b"ha/d23/v1/body/request",  len=32)
    k_response = HKDF-SHA256(ikm=secret_utf8, salt=HKDF_SALT,
                             info=b"ha/d23/v1/body/response", len=32)
    key_id     = base64url_unpadded(HKDF-SHA256(..., info=b"ha/d23/v1/key-id",
                                                len=8))

``ikm`` is the EXACT UTF-8 bytes of the instance's shared secret after
stripping surrounding whitespace -- the secret is stored as an ASCII string in
a file with a trailing newline, the server strips it, and the client trims the
string a person pasted. Pinning ``secret_utf8_b64`` in the vectors is what
stops the two languages disagreeing about that.

The key id is DERIVED, not configured. Two instances on one box hold different
secrets and therefore publish different key ids with nothing to keep in sync,
and a client needs no extra field at pairing time. Eight bytes of HKDF output
is not invertible to a 32-byte random secret.

AAD, length-prefixed rather than delimited, because a target can contain any
byte a percent-encoding can express and a delimiter scheme has to answer for
that::

    aad = version(1)
        || u32be(len(direction)) || direction     b"request" | b"response"
        || u32be(len(method))    || method        uppercase ASCII
        || u32be(len(target))    || target        raw percent-encoded path,
                                                  plus b"?" + raw query bytes
                                                  when the query is non-empty
        || u32be(len(key_id))    || key_id        ASCII
        || u64be(timestamp_ms)

A response binds the METHOD AND TARGET OF THE REQUEST IT ANSWERS, so a captured
answer cannot be replayed as the answer to a different call.

The target is the externally visible one: ``scope["path"]`` is percent-DECODED
and excludes the query, so binding it alone would give ``/v1/today?date=A`` and
``?date=B`` the same AAD. Build it from ``raw_path`` (or ``root_path + path``
percent-encoded the same way) and the raw ``query_string``.

Skew window: 600 seconds either side. THE SCOUTING NOTE'S DERIVATION IS WRONG
AND THE NUMBER SURVIVES ANYWAY. It argued 10 minutes from a measured 364-second
``/v1/ask``, but that 364 s is server processing: it happens after the request
timestamp has already been checked and before the response is stamped, so it
never enters the budget in either direction. What does enter is body transfer
plus clock drift. An ingest page is around 8 MiB by the client's own estimate;
at 200 kbit/s that is 335 s of upload before the receiver sees the first byte
of the envelope, which a 300-second window would refuse. The failure of a
too-tight window is the expensive one: a refused ingest makes the client
withhold its HealthKit anchor and the sync stalls with no error anyone sees. A
too-loose one buys a replay window against an adversary who already holds the
ciphertext, where an ingest replay is idempotent by the dedupe identity and an
ask replay re-asks a question whose answer is still unreadable. So: 600.

Symmetric, because a phone clock can be fast as well as slow.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import struct
import sys
from pathlib import Path

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

VERSION = 1
HKDF_SALT = b"ha-d23-body-aead-v1"
INFO_REQUEST = b"ha/d23/v1/body/request"
INFO_RESPONSE = b"ha/d23/v1/body/response"
INFO_KEY_ID = b"ha/d23/v1/key-id"
KEY_BYTES = 32
KEY_ID_BYTES = 8
NONCE_BYTES = 12
TAG_BYTES = 16
HEADER_BYTES = 1 + 8 + NONCE_BYTES
SKEW_SECONDS = 600

DIRECTIONS = {"request": INFO_REQUEST, "response": INFO_RESPONSE}

# Obviously not an instance secret. 43 characters, the shape token_urlsafe(32)
# produces, so the vectors exercise the real length rather than a toy one.
VECTOR_SECRET = "d23-vector-secret-not-a-real-instance-value"
OTHER_SECRET = "d23-vector-secret-belonging-to-another-inst"

# 2026-09-16T20:00:00Z. Fixed so a replay is deterministic.
BASE_MS = 1789588800000


# --- HKDF-SHA256, written out rather than imported ---------------------------
# RFC 5869. Extract-then-expand in eight lines; doing it by hand here means the
# vectors do not inherit a mistake from the same helper the shipped code uses.

def hkdf_sha256(ikm: bytes, salt: bytes, info: bytes, length: int) -> bytes:
    prk = hmac.new(salt, ikm, hashlib.sha256).digest()
    out = b""
    block = b""
    counter = 1
    while len(out) < length:
        block = hmac.new(prk, block + info + bytes([counter]),
                         hashlib.sha256).digest()
        out += block
        counter += 1
    return out[:length]


def b64u(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def b64(raw: bytes) -> str:
    return base64.b64encode(raw).decode("ascii")


def secret_bytes(secret: str) -> bytes:
    return secret.strip().encode("utf-8")


def body_key(secret: str, direction: str) -> bytes:
    return hkdf_sha256(secret_bytes(secret), HKDF_SALT,
                       DIRECTIONS[direction], KEY_BYTES)


def key_id(secret: str) -> str:
    return b64u(hkdf_sha256(secret_bytes(secret), HKDF_SALT,
                            INFO_KEY_ID, KEY_ID_BYTES))


def build_aad(direction: str, method: str, target: bytes, kid: str,
              timestamp_ms: int) -> bytes:
    parts = [bytes([VERSION])]
    for field in (direction.encode("ascii"), method.encode("ascii"), target,
                  kid.encode("ascii")):
        parts.append(struct.pack(">I", len(field)))
        parts.append(field)
    parts.append(struct.pack(">Q", timestamp_ms))
    return b"".join(parts)


def seal(secret: str, direction: str, method: str, target: bytes,
         plaintext: bytes, timestamp_ms: int, nonce: bytes) -> tuple[bytes, bytes]:
    """Return (wire, aad). `nonce` is injected ONLY so a vector reproduces."""
    assert len(nonce) == NONCE_BYTES
    kid = key_id(secret)
    aad = build_aad(direction, method, target, kid, timestamp_ms)
    sealed = AESGCM(body_key(secret, direction)).encrypt(nonce, plaintext, aad)
    wire = bytes([VERSION]) + struct.pack(">Q", timestamp_ms) + nonce + sealed
    return wire, aad


# --- the deterministic large body --------------------------------------------
# Spelled as a recipe so the fixture stays a few tens of KB instead of carrying
# 1.1 MiB twice over in base64. Both languages can build it in three lines, and
# `plaintext_sha256` plus `wire_sha256` keep it byte-exact.

LARGE_PATTERN = bytes(range(64))
LARGE_LENGTH = 1_200_000


def large_body() -> bytes:
    reps = LARGE_LENGTH // len(LARGE_PATTERN) + 1
    return (LARGE_PATTERN * reps)[:LARGE_LENGTH]


def _nonce(index: int) -> bytes:
    """Fixed, distinct, and never produced by the shipped sealer."""
    return b"D23VEC" + struct.pack(">IH", index, index)


def _case(index: int, name: str, *, direction: str, method: str, target: str,
          plaintext: bytes, expected: str, note: str,
          secret: str = VECTOR_SECRET, timestamp_ms: int | None = None,
          verify_at_ms: int = BASE_MS, inline: bool = True,
          mutate=None, verify_direction: str | None = None,
          verify_method: str | None = None,
          verify_target: str | None = None) -> dict:
    timestamp_ms = BASE_MS if timestamp_ms is None else timestamp_ms
    target_bytes = target.encode("utf-8")
    wire, aad = seal(secret, direction, method, target_bytes, plaintext,
                     timestamp_ms, _nonce(index))
    if mutate is not None:
        wire = mutate(wire)
    case: dict = {
        "name": name,
        "note": note,
        "direction": direction,
        "method": method,
        "target": target,
        "key_id": key_id(secret),
        "timestamp_ms": timestamp_ms,
        "verify_at_ms": verify_at_ms,
        "expected": expected,
        "nonce_b64": b64(_nonce(index)),
        "aad_b64": b64(aad),
        "wire_sha256": hashlib.sha256(wire).hexdigest(),
        "wire_length": len(wire),
        "plaintext_sha256": hashlib.sha256(plaintext).hexdigest(),
        "plaintext_length": len(plaintext),
    }
    if inline:
        case["plaintext_b64"] = b64(plaintext)
        case["wire_b64"] = b64(wire)
    else:
        case["plaintext_recipe"] = {
            "kind": "repeat_pattern",
            "pattern_b64": b64(LARGE_PATTERN),
            "length": len(plaintext),
        }
    # A negative case is verified against something OTHER than what it was
    # sealed under; say which, so the replayer does not have to infer it.
    if verify_direction or verify_method or verify_target:
        case["verify_as"] = {
            "direction": verify_direction or direction,
            "method": verify_method or method,
            "target": verify_target or target,
        }
    if secret != VECTOR_SECRET:
        case["sealed_with_secret_utf8_b64"] = b64(secret_bytes(secret))
    return case


def _build_cases() -> list[dict]:
    cases = []
    i = 0

    def add(**kwargs):
        nonlocal i
        i += 1
        cases.append(_case(i, **kwargs))

    add(name="request_empty_body", direction="request", method="POST",
        target="/v1/ask", plaintext=b"", expected="ok",
        note="An empty body still produces a 37-byte envelope. A receiver that "
             "treats zero-length as 'nothing to decrypt' accepts a stripped "
             "body as if it were an encrypted one.")
    add(name="request_one_byte", direction="request", method="POST",
        target="/v1/ingest", plaintext=b"{", expected="ok",
        note="One byte, to pin that the length prefix and the tag offset do "
             "not assume a block boundary.")
    add(name="request_small_json", direction="request", method="POST",
        target="/v1/ask",
        plaintext=json.dumps({"question": "how has my running been",
                              "conversation_id": "c-1"},
                             separators=(",", ":")).encode("utf-8"),
        expected="ok",
        note="The ordinary ask shape.")
    add(name="request_non_ascii_utf8", direction="request", method="POST",
        target="/v1/ask",
        plaintext="{\"question\":\"¿cómo va mi ritmo? naïve café 🏃 走り\"}"
                  .encode("utf-8"),
        expected="ok",
        note="Non-ASCII UTF-8 in the body. Swift's String and Python's str "
             "must agree on the bytes before either encrypts them.")
    add(name="request_query_bearing_target", direction="request", method="GET",
        target="/v1/today?date=2026-09-16&tz=America%2FNew_York",
        plaintext=b"", expected="ok",
        note="THE CASE THE SCHEME WAS UNDERSPECIFIED ON. scope['path'] is "
             "percent-DECODED and carries no query, so binding it alone gives "
             "?date=A and ?date=B the same AAD. The target here is the raw "
             "percent-encoded path plus '?' plus the raw query bytes, and the "
             "%2F must NOT be decoded to '/'.")
    add(name="request_large_1_2mb", direction="request", method="POST",
        target="/v1/ingest", plaintext=large_body(), expected="ok",
        inline=False,
        note="1,200,000 bytes, given as a recipe rather than 1.6 MB of base64. "
             "Build pattern_b64 repeated to `length`, then match "
             "plaintext_sha256 before encrypting and wire_sha256 after.")
    add(name="response_small_json", direction="response", method="POST",
        target="/v1/ask",
        plaintext=json.dumps({"answer": "a narration", "mode": "answer"},
                             separators=(",", ":")).encode("utf-8"),
        expected="ok",
        note="The response direction binds the METHOD AND TARGET OF THE "
             "REQUEST IT ANSWERS, so an answer cannot be replayed as the "
             "answer to a different call.")
    add(name="response_empty_body", direction="response", method="POST",
        target="/v1/ask/delivered", plaintext=b"", expected="ok",
        note="A 204-shaped response still crosses the wire as an envelope.")

    # --- negatives -----------------------------------------------------------
    add(name="neg_wrong_key", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        secret=OTHER_SECRET, expected="error:d23_decrypt",
        note="Sealed under a DIFFERENT instance's secret. A receiver that "
             "accepts this has no per-instance isolation. Its key_id also "
             "differs, which is the cheap check; the tag is the real one.")
    add(name="neg_expired_timestamp", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        timestamp_ms=BASE_MS - (SKEW_SECONDS + 1) * 1000,
        expected="error:d23_skew",
        note="601 s old against verify_at_ms. 600 s exactly must still be "
             "accepted -- the boundary is inclusive.")
    add(name="neg_future_timestamp", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        timestamp_ms=BASE_MS + (SKEW_SECONDS + 1) * 1000,
        expected="error:d23_skew",
        note="A fast phone clock, not an attack. The window is symmetric.")
    add(name="skew_boundary_inclusive", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        timestamp_ms=BASE_MS - SKEW_SECONDS * 1000, expected="ok",
        note="Exactly 600 s old and ACCEPTED. Without this the window could "
             "be off by one in either direction and every other vector would "
             "still pass.")
    add(name="neg_tampered_aad_target", direction="request", method="POST",
        target="/v1/today?date=2026-09-16", plaintext=b"{}",
        verify_target="/v1/today?date=2026-01-01",
        expected="error:d23_decrypt",
        note="Sealed for one query, verified against another. This is the "
             "vector that fails if AAD binds only scope['path'].")
    add(name="neg_tampered_aad_method", direction="request", method="POST",
        target="/v1/ingest", plaintext=b"{}", verify_method="PUT",
        expected="error:d23_decrypt",
        note="Same bytes, different verb.")
    add(name="neg_direction_confusion", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{}", verify_direction="response",
        expected="error:d23_decrypt",
        note="A request envelope replayed as a response. Fails only if the "
             "two info strings really differ, which is what makes this the "
             "vector that catches a copy-pasted info constant.")
    add(name="neg_wrong_version_byte", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{}",
        mutate=lambda w: bytes([0x02]) + w[1:],
        expected="error:d23_version",
        note="A distinct error, because the client's remedy is 'update the "
             "app', not 'check your clock'. Note the AAD also carries the "
             "version, so this cannot be answered by decrypting first.")
    add(name="neg_tampered_tag", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        mutate=lambda w: w[:-1] + bytes([w[-1] ^ 0x01]),
        expected="error:d23_decrypt",
        note="One flipped bit in the tag.")
    add(name="neg_tampered_ciphertext", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        mutate=lambda w: w[:HEADER_BYTES] + bytes([w[HEADER_BYTES] ^ 0x80])
                         + w[HEADER_BYTES + 1:],
        expected="error:d23_decrypt",
        note="One flipped bit in the ciphertext.")
    add(name="neg_tampered_wire_timestamp", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        mutate=lambda w: w[:1] + struct.pack(">Q", BASE_MS) + w[9:],
        timestamp_ms=BASE_MS - (SKEW_SECONDS + 1) * 1000,
        expected="error:d23_decrypt",
        note="An expired envelope whose CLEAR timestamp has been rewritten to "
             "a fresh one. It now passes the skew check and must fail the tag "
             "-- which is the whole reason the timestamp is in the AAD too. A "
             "receiver that checks skew and then forgets to bind it returns ok "
             "here.")
    add(name="neg_truncated", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{\"question\":\"x\"}",
        mutate=lambda w: w[:HEADER_BYTES + TAG_BYTES - 1],
        expected="error:d23_truncated",
        note="Shorter than header + tag. Must be named, not surfaced as a "
             "decrypt failure and not as a 500.")
    add(name="neg_empty_wire", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{}", mutate=lambda w: b"",
        expected="error:d23_missing",
        note="No body at all where one was required. On a `required` instance "
             "this is the plaintext-body refusal: distinct from truncated, "
             "because the remedy differs.")
    add(name="neg_plaintext_json_body", direction="request", method="POST",
        target="/v1/ask", plaintext=b"{}",
        mutate=lambda w: b"{\"question\":\"sent in the clear\"}",
        expected="error:d23_missing",
        note="A literal plaintext JSON body arriving at a `required` instance. "
             "Its first byte is 0x7b, not a known version. THE REFUSAL MUST "
             "NOT ECHO ANY OF IT: this is the vector that also pins that the "
             "error body carries no request bytes.")

    return cases


def build_document() -> dict:
    return {
        "$comment": [
            "D23 body AEAD, version 1. Cross-language vectors: the server",
            "publishes this file and the iOS client replays it. Generated by",
            "scripts/d23_reference.py, which is a SECOND implementation and",
            "imports nothing from health_advisor -- a vector file produced by",
            "the code it tests is an instrument whose green means unmeasured.",
            "Regenerate with: python scripts/d23_reference.py --out <this>",
            "No production secret appears here. The nonces are a fixed counter",
            "so the file is reproducible; the shipped sealer uses os.urandom",
            "and exposes an injectable nonce only to its tests.",
        ],
        "version": VERSION,
        "algorithm": "AES-256-GCM",
        "kdf": "HKDF-SHA256",
        "hkdf_salt_b64": b64(HKDF_SALT),
        "info_request_b64": b64(INFO_REQUEST),
        "info_response_b64": b64(INFO_RESPONSE),
        "info_key_id_b64": b64(INFO_KEY_ID),
        "key_bytes": KEY_BYTES,
        "key_id_bytes": KEY_ID_BYTES,
        "key_id_encoding": "base64url, unpadded",
        "nonce_bytes": NONCE_BYTES,
        "tag_bytes": TAG_BYTES,
        "header_bytes": HEADER_BYTES,
        "skew_window_seconds": SKEW_SECONDS,
        "skew_boundary": "inclusive: |now - timestamp| <= skew_window_seconds",
        "wire_layout": ("version(1) || timestamp_ms(uint64 BE) || nonce(12) "
                        "|| ciphertext||tag(16)"),
        "aad_b64_is": ("the AAD THE SEALER USED, built from the case's own "
                      "top-level direction/method/target/key_id/timestamp_ms. "
                      "A verifier must BUILD ITS OWN from what it observes on "
                      "the wire and from `verify_as` when present -- for a "
                      "mutated or misdirected case the two differ, and that "
                      "difference is the test."),
        "empty_body_rule": ("the PRIMITIVE refuses empty bytes with "
                            "d23_missing. The MIDDLEWARE never hands it a "
                            "request that carries no body at all (a GET), and "
                            "always seals the response. Conflating the two "
                            "makes a stripped body look like a bodyless "
                            "request."),
        "aad_layout": ("version(1) || u32be(len)||direction || "
                       "u32be(len)||method || u32be(len)||target || "
                       "u32be(len)||key_id || u64be(timestamp_ms)"),
        "target_rule": ("raw percent-encoded path, plus '?' and the raw query "
                        "bytes when the query string is non-empty; never the "
                        "percent-decoded path, and never the path alone"),
        "response_binding": ("a response binds the method and target of the "
                             "request it answers"),
        "secret_utf8_b64": b64(secret_bytes(VECTOR_SECRET)),
        "key_id": key_id(VECTOR_SECRET),
        "key_request_b64": b64(body_key(VECTOR_SECRET, "request")),
        "key_response_b64": b64(body_key(VECTOR_SECRET, "response")),
        "errors": {
            "d23_missing": "no envelope where one is required",
            "d23_version": "leading byte is not a supported version",
            "d23_truncated": "shorter than header + tag",
            "d23_skew": "timestamp outside the window",
            "d23_decrypt": "authentication failed: wrong key, wrong AAD, or "
                           "tampered bytes",
        },
        "cases": _build_cases(),
    }


def self_check(doc: dict) -> None:
    """Replay the file the way the other language will, and fail loudly."""
    for case in doc["cases"]:
        if "wire_b64" not in case:
            continue
        wire = base64.b64decode(case["wire_b64"])
        assert hashlib.sha256(wire).hexdigest() == case["wire_sha256"], case["name"]
        assert len(wire) == case["wire_length"], case["name"]
    large = [c for c in doc["cases"] if c["name"] == "request_large_1_2mb"][0]
    body = large_body()
    assert hashlib.sha256(body).hexdigest() == large["plaintext_sha256"]
    # Every `ok` case must actually open under the published parameters.
    for case in doc["cases"]:
        if case["expected"] != "ok":
            continue
        wire = (base64.b64decode(case["wire_b64"]) if "wire_b64" in case
                else seal(VECTOR_SECRET, case["direction"], case["method"],
                          case["target"].encode("utf-8"), body,
                          case["timestamp_ms"],
                          base64.b64decode(case["nonce_b64"]))[0])
        aad = base64.b64decode(case["aad_b64"])
        plain = AESGCM(body_key(VECTOR_SECRET, case["direction"])).decrypt(
            wire[9:21], wire[21:], aad)
        assert hashlib.sha256(plain).hexdigest() == case["plaintext_sha256"], \
            case["name"]
    print(f"self-check ok: {len(doc['cases'])} cases, "
          f"{sum(1 for c in doc['cases'] if c['expected'] == 'ok')} ok, "
          f"{sum(1 for c in doc['cases'] if c['expected'] != 'ok')} negative")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args(argv)
    doc = build_document()
    self_check(doc)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8")
    print(f"wrote {args.out} ({args.out.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
